package com.web.exceptions;

public enum UserExceptionType {

	CHANGE_PASSWORD, DELETE_USER, EXISTING_USERNAME, ACTIVATION_CODE, EXISTING_EMAIL, EMAIL_CHANGE_CODE, USER_NOT_fOUND, EMAIL_NOT_ACTIVATED, WRONG_PASSWORD_RECOVER_CODE
	
}
